import type { CatalogRecordSet } from "./types";

/** Development/test fixture only. Every value is synthetic and non-operational. */
export const syntheticDemoCatalogRecords: CatalogRecordSet = {
  source: "synthetic-demo",
  products: [
    {
      id: "demo-product-alpha",
      slug: "synthetic-reference-alpha",
      name: "Synthetic Reference Alpha — Demo Only",
      packageForm: "Synthetic sealed reference unit",
      materialIdentity: "Synthetic identity record",
      policyGroupId: "demo-policy-group",
      status: "active",
    },
    {
      id: "demo-product-beta",
      slug: "synthetic-reference-beta",
      name: "Synthetic Reference Beta — Demo Only",
      packageForm: "Synthetic sealed reference unit",
      materialIdentity: "Synthetic identity record",
      policyGroupId: "demo-policy-group",
      status: "active",
    },
  ],
  prices: [
    {
      id: "demo-price-alpha",
      productId: "demo-product-alpha",
      version: 1,
      amountMinor: 2400,
      currency: "USD",
      effectiveAt: "2026-01-01T00:00:00.000Z",
      supersededAt: null,
    },
    {
      id: "demo-price-beta",
      productId: "demo-product-beta",
      version: 1,
      amountMinor: 1800,
      currency: "USD",
      effectiveAt: "2026-01-01T00:00:00.000Z",
      supersededAt: null,
    },
  ],
  lots: [
    {
      id: "demo-lot-alpha",
      productId: "demo-product-alpha",
      supplierName: "SYNTHETIC SUPPLIER — TEST ONLY",
      supplierLotCode: "DEMO-LOT-ALPHA",
      availableQuantity: 12,
      status: "released",
      analyticalMethod: "Synthetic analytical method record",
    },
    {
      id: "demo-lot-beta",
      productId: "demo-product-beta",
      supplierName: "SYNTHETIC SUPPLIER — TEST ONLY",
      supplierLotCode: "DEMO-LOT-BETA",
      availableQuantity: 7,
      status: "released",
      analyticalMethod: null,
    },
  ],
  coaDocuments: [
    {
      id: "demo-coa-alpha",
      lotId: "demo-lot-alpha",
      storageKey: "synthetic-demo/alpha-record.pdf",
      active: true,
      public: true,
      issuedAt: "2026-07-01T00:00:00.000Z",
    },
  ],
  claims: [
    {
      id: "demo-claim-alpha",
      productId: "demo-product-alpha",
      text: "A synthetic analytical record is linked to this demo lot.",
      kind: "analytical",
      lotId: "demo-lot-alpha",
      coaDocumentId: "demo-coa-alpha",
      active: true,
    },
  ],
  promotions: [
    {
      id: "demo-discount",
      name: "Synthetic percentage display — Demo Only",
      kind: "discount",
      status: "active",
      startsAt: null,
      endsAt: null,
      configuration: { basisPoints: 1000 },
    },
    {
      id: "demo-bundle",
      name: "Synthetic bundle display — Demo Only",
      kind: "bundle",
      status: "active",
      startsAt: null,
      endsAt: null,
      configuration: {
        productIds: ["demo-product-alpha", "demo-product-beta"],
        bundleAmountMinor: 3600,
        currency: "USD",
      },
    },
    {
      id: "demo-subscription",
      name: "Synthetic subscription display — Demo Only",
      kind: "subscription",
      status: "active",
      startsAt: null,
      endsAt: null,
      configuration: { interval: "month", intervalCount: 1 },
    },
    {
      id: "demo-loyalty",
      name: "Synthetic loyalty display — Demo Only",
      kind: "loyalty",
      status: "active",
      startsAt: null,
      endsAt: null,
      configuration: { pointsPerDollar: 2 },
    },
    {
      id: "demo-cross-sell",
      name: "Synthetic related-record display — Demo Only",
      kind: "cross_sell",
      status: "active",
      startsAt: null,
      endsAt: null,
      configuration: { productIds: ["demo-product-beta"] },
    },
  ],
  promotionTargets: [
    ...[
      "demo-discount",
      "demo-bundle",
      "demo-subscription",
      "demo-loyalty",
      "demo-cross-sell",
    ].map((promotionId) => ({
      promotionId,
      targetKind: "product" as const,
      productId: "demo-product-alpha",
      policyGroupId: null,
    })),
  ],
};
